### ISSUE TITLE
Variant forms

### ISSUE THREAD

**Issue by PromiseDodzi** [languageorphans/heathdogon#13]
We realize that variants are not included in the data that is aligned.
For instance for the two forms for "domestic animal(esp. livestock)" in JamsayDouentza , only one is tokenized and used.
We have the same case for Mombo, and some few more in the data.
Is there a way we can make the workflow take these variants into account?

![Capture_1](https://github.com/languageorphans/heathdogon/assets/128131568/9cf06ffc-158e-4366-958f-411a4a8f5e28)
![Capture_2](https://github.com/languageorphans/heathdogon/assets/128131568/276c44ae-9079-4f3b-add5-a3135fda93af)

**Comment by LinguList** [comment]
As far as I read the code, we account for variants where you have manually extracted plurals, but otherwise only check one form. My suggestion is to first count quickly about how many variants we talk here, before adding them computationally, since it may be easier to handle variants later on, when you start editing alignments manually. Right now, it may well be an overkill. 

What you can of course also do is setting `first_form_only=False` in the CLDF code and then re-run and check what you get. This handles if variants are in fact used or not.

**Comment by PromiseDodzi** [comment]
Alright.
I'll do that.

**Comment by PromiseDodzi** [comment]
> As far as I read the code, we account for variants where you have manually extracted plurals, but otherwise only check one form. My suggestion is to first count quickly about how many variants we talk here, before adding them computationally, since it may be easier to handle variants later on, when you start editing alignments manually. Right now, it may well be an overkill.
> 
> What you can of course also do is setting `first_form_only=False` in the CLDF code and then re-run and check what you get. This handles if variants are in fact used or not.

I have been taking a critical relook at the alignments to understand how varied forms are handled. It seems that until during alignments, they are in the data. However, Lingpy seems to select a form per language during alignments. For instance, the first picture below is all the forms for 'domestic animal'. Where the VARID has 1.0, the value in that row is the variant. In the alignments, you will see that all languages, except Mombo align the variant forms and not the first form (the form with a 0.0 VARID). When I look at other alignments, I see that the choices are not all 0.0 or 1.0. The algorithm seems to pick one form over the other according to a certain criteria. Could you please help me understand why one form is being picked over the other, instead of the two being aligned?
![a](https://github.com/user-attachments/assets/c19c04f9-f566-4025-9996-6ac6a4cb62b1)
![1](https://github.com/user-attachments/assets/1ffecef9-de14-4058-b4bb-89d58325a9bb)

**Comment by PromiseDodzi** [comment]
> We realize that variants are not included in the data that is aligned. For instance for the two forms for "domestic animal(esp. livestock)" in JamsayDouentza , only one is tokenized and used. We have the same case for Mombo, and some few more in the data. Is there a way we can make the workflow take these variants into account?
> 
> ![Capture_1](https://private-user-images.githubusercontent.com/128131568/344704429-9cf06ffc-158e-4366-958f-411a4a8f5e28.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTM5NTksIm5iZiI6MTcyNDA1MzY1OSwicGF0aCI6Ii8xMjgxMzE1NjgvMzQ0NzA0NDI5LTljZjA2ZmZjLTE1OGUtNDM2Ni05NThmLTQxMWE0YThmNWUyOC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNzQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzM3MWE2MGY0MzY2ZjgzOTM5NGE4NWNmNDM1YzQ5YzUyNWE3ZjdlM2E0YWQ5MDFkMDE5Nzk5ODNiZTMzNzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nxVf09qUUPnWMj6IiSlx2yp6r2-n97OAiAj_Z-2wb3Y) ![Capture_2](https://private-user-images.githubusercontent.com/128131568/344704451-276c44ae-9079-4f3b-add5-a3135fda93af.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTM5NTksIm5iZiI6MTcyNDA1MzY1OSwicGF0aCI6Ii8xMjgxMzE1NjgvMzQ0NzA0NDUxLTI3NmM0NGFlLTkwNzktNGYzYi1hZGQ1LWEzMTM1ZmRhOTNhZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNzQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmVlYmYyNGQ0ZTg1YzY3ZmJiNGZlZjk3NmEwOWY5NDg1YmI5YTI3NGQzODVhNzgyNzFiMTI2YTc1MmM3NmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pf6zoRs_wbM8mmqqMsFPGj0DGkde9N5F6OYiuPNfsnU)

@LinguList Thank you.
After modifying the CLDF code, where the variant forms are judged by Lingpy as (partially-)cognate, they are aligned.
Thank you
